### ISSUE TITLE
Feature suggestion: Public IP check

### ISSUE THREAD

**Issue by sesam** [dewdeded/GrinHelper#2]
Maybe a menu option to help testing if the grin server and grin wallet listen is publicly reachable from internet could be very useful.

  1. find external IP

@photis suggests
`netstat -an | grep -e 13413 -e 13414 -e 13415`
`myip="$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com)"`
`echo "My WAN/Public IP address: ${myip}"`

  2. connect from the outside and see if grin responds properly
TODO

**Comment by dewdeded** [comment]
Thanks, good idea. I add that soon.

**Comment by dewdeded** [comment]
Added.

####### Sample Output 1 #######
Please select an option: c2

Checking if Grins ports are publicly reachable ...

Standard port 13413 is open.
Standard port 13414 is open.
Standard port 13415 is open.

Checking if port 13413 is publicly reachable.
Fail, port 13413 is NOT reachable.

Checking if port 13414 is publicly reachable.
Success, port 13414 is reachable.

Checking if port 13415 is publicly reachable.
Success, port 13415 is reachable.

Press ENTER To Return
#############################

####### Sample Output 2 #######
Please select an option: c2

Checking if Grins ports are publicly reachable ...

Standard port 13413 is open.
Standard port 13414 is open.
Standard port 13415 is NOT open.
Checking if port 13413 is publicly reachable.
Fail, port 13413 is NOT reachable.
Checking if port 13414 is publicly reachable.
Fail, port 13414 is NOT reachable.
Checking if port 13415 is publicly reachable.
Fail, port 13415 is NOT reachable.

Press ENTER To Return
#############################
